# This is a basic workflow to help you get started with Actions

name: workflow_flaky_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:

  build_1:
    runs-on: ubuntu-latest

    steps:
      - name: git clone 
        run: git clone https://github.com/spdx/tools
      
      - name: cd
        run: cd tools
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: spdx/tools
          ref: cf965bc2fa99e1c5ca23f992f18cef48c08dec9f
      
      - name: test-compile
        run: mvn test-compile -pl . -am
      
      - name: test
        run: mvn -pl . test -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol
      
      - name: flaky-test
        run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol -DnondexRuns=10
  build_2:
    runs-on: ubuntu-latest

    steps:
      - name: git clone 
        run: git clone https://github.com/Huawei/vCenter_Plugin_DME
      
      - name: cd
        run: cd vCenter_Plugin_DME
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: Huawei/vCenter_Plugin_DME
          ref: fa077ef3c8ee052afc01084bc5aaae7c3b4518a4
      
      - name: test-compile
        run: mvn test-compile -pl dmestore-service -am
      
      - name: test
        run: mvn -pl dmestore-service test -Dtest=com.huawei.dmestore.services.DmeAccessServiceImplTest#testAccess
  
      - name: flaky-test
        run: mvn -pl dmestore-service edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.huawei.dmestore.services.DmeAccessServiceImplTest#testAccess
