# This is a basic workflow to help you get started with Actions

name: workflow_flaky_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:

  build_1:
    runs-on: ubuntu-latest

    steps:
      - name: git clone 
        run: git clone https://github.com/spdx/tools
      
      - name: cd
        run: cd tools
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: spdx/tools
          ref: cf965bc2fa99e1c5ca23f992f18cef48c08dec9f
      
      - name: test-compile
        run: mvn test-compile -pl . -am
      
      - name: test
        run: mvn -pl . test -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol
      
      - name: flaky-test
        run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol -DnondexRuns=10
  build_2:
    runs-on: ubuntu-latest

    steps:
      - name: git clone 
        run: git clone https://github.com/adobe/aem-core-wcm-components
      
      - name: cd
        run: cd aem-core-wcm-components
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: adobe/aem-core-wcm-components
          ref: 5f29cc86b17b6db36cc617805295eb951b6504a1
      
      - name: test-compile
        run: mvn test-compile -pl bundles/core -am
      
      - name: test
        run: mvn -pl bundles/core test -Dtest=com.adobe.cq.wcm.core.components.internal.servlets.contentfragment.ElementsDataSourceServletTest#testComponentPathStructured
  
      - name: flaky-test
        run: mvn -pl bundles/core edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=com.adobe.cq.wcm.core.components.internal.servlets.contentfragment.ElementsDataSourceServletTest#testComponentPathStructured
