# This is a basic workflow to help you get started with Actions

name: workflow_flaky_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:

  build_1:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: git clone 
        run: git clone https://github.com/spdx/tools
      
      - name: cd
        run: cd tools
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: spdx/tools
          ref: cf965bc2fa99e1c5ca23f992f18cef48c08dec9f
      
      - name: test-compile
        run: mvn test-compile -pl . -am
      
      - name: test
        run: mvn -pl . test -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol
      
      - name: flaky-test
        run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol -DnondexRuns=10
  build_2:
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
    
      - name: git clone 
        run: git clone https://github.com/apache/flink
      
      - name: cd
        run: cd flink
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: apache/flink
          ref: 23c9b5ac50d04d28a34a87c78eb2d3331c06b74b
      
      - name: test-compile
        run: mvn test-compile -pl flink-connectors/flink-connector-kafka-base -am
      
      - name: test
        run: mvn -pl flink-connectors/flink-connector-kafka-base test -Dtest=org.apache.flink.table.descriptors.KafkaTest#testValidation
  
      - name: flaky-test
        run: mvn -pl flink-connectors/flink-connector-kafka-base edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.flink.table.descriptors.KafkaTest#testValidation
