# This is a basic workflow to help you get started with Actions

name: workflow_flaky_tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

jobs:

  build_1:
    runs-on: ubuntu-latest

    steps:
      - name: git clone 
        run: git clone https://github.com/spdx/tools
      
      - name: cd
        run: cd tools
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: spdx/tools
          ref: cf965bc2fa99e1c5ca23f992f18cef48c08dec9f
      
      - name: test-compile
        run: mvn test-compile -pl . -am
      
      - name: test
        run: mvn -pl . test -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol
      
      - name: flaky-test
        run: mvn -pl . edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.spdx.compare.TestPackageSheet#testDeclaredLicenseCol -DnondexRuns=10
  build_2:
    runs-on: ubuntu-latest

    steps:
      - name: git clone 
        run: git clone https://github.com/apache/openwebbeans
      
      - name: cd
        run: cd openwebbeans
        
      - name: Check out repository
        uses: actions/checkout@v3
        with:
          repository: apache/openwebbeans
          ref: 424af4bb7285b806d3e3efe5020cd3e440e0a4ff
      
      - name: test-compile
        run: mvn test-compile -pl webbeans-impl -am
      
      - name: test
        run: mvn -pl webbeans-impl test -Dtest=org.apache.webbeans.test.annotation.binding.BeanCacheKeyUnitTest#testEquals2AnnotationsUnorderedParam
      
      - name: flaky-test
        run: mvn -pl webbeans-impl edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.webbeans.test.annotation.binding.BeanCacheKeyUnitTest#testEquals2AnnotationsUnorderedParam
